production:
  :concurrency: 5
:queues:
  - default
:schedule:
  end_billing_periods:
    cron: '5 0 * * * UTC'
    class: EndBillingPeriodsJob
  end_trials:
    cron: '10 0 * * * UTC'
    class: EndTrialsJob
